### ISSUE TITLE
issue with model

### ISSUE THREAD

**Issue by BrahianVT** [badboysm890/Youtube2Blog#1]
trying to use in windows 10 ad it didn't work
I traced the error to these lines:
from transformers import T5ForConditionalGeneration,T5Tokenizer
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
models = T5ForConditionalGeneration.from_pretrained("Michau/t5-base-en-generate-headline")
tokenizer = T5Tokenizer.from_pretrained("Michau/t5-base-en-generate-headline")
the response is:
![image](https://github.com/huggingface/transformers/assets/12876560/46c229cf-aea1-4855-a36a-c9f21533e250)

Any help with this will be very appreciated

Regards

**Comment by badboysm890** [comment]
I would suggest you to download the pre-trained weights from the Hugging Face and place it  in the path or try WSL and it should work

**Comment by BrahianVT** [comment]
yeah update for future reference in windows, in order to make it works I installed whisper from main branch, and also install transformers again see this: https://github.com/huggingface/transformers/issues/24470
With this worked in line-command. But never worked with the UI, maybe the project need a better guide to install and use it.
